### ISSUE TITLE
Testing an array of promise middleware

### ISSUE THREAD

**Issue by reggi** [express-promise-router/express-promise-router#14]
I'm trying to work out a way of testing an array of promised middleware and I came up with this contraption. I was wondering if there was something that you had in your arsenal. Thoughts?

``` javascript
function mapRoute(req, res, middlewares){
  var errors = []
  var next = []
  var route = false
  return Promise.map(middlewares, function(middleware) {
    return middleware(req, res).then(function(response){
      if(response == "route") route = true
      if(response == "next") next.push("next")
    }).catch(function(e){
      errors.push(e)
    })
  }, {concurrency: 1})
  .then(function(){
    if(route) return "route"
    if(errors) throw errors[0]
    if(next.length == middlewares.length) return "next"
    return false
  })
}
```

**Comment by reggi** [comment]
```
function mapRoute(req, res, middlewares){
  function createNext(index){
    return Promise.resolve()
      .then(function(){
        return middlewares[index](req, res)
      })
      .then(function(action){
        if(action == "route") return "route"
        if(action == "next"){
          if(middlewares.length-1 >= index+1){
            return createNext(index+1)
          }
        }
        return "done"
      })
  }
  return createNext(0)
}
```

The above works way better.

**Comment by alex-whitney** [comment]
All of this behavior should already be captured in express / express-promise-router, so I'm not sure it necessarily makes sense to reproduce it in tests.

I would suggest taking a look at [supertest](https://github.com/visionmedia/supertest) so that you can test your routes without worrying about how your handlers and middleware are structured.

**Comment by reggi** [comment]
Here's another example of something I want to do without testing.

Let's say I have a chain of middleware for one route, like this.

```javascript
app.use("/page", [
  middleware.validateQuery(),
  middleware.processPage(),
  middleware.retrieveFromDb(),
  middleware.setValue(),
])
```

And not In a new route I want to use this chain from above conditionally.

```javascript
var chain = [
  middleware.checkMethod(),
  middleware.validateQuery(),
  middleware.processPage(),
  middleware.retrieveFromDb(),
  middleware.setValue(),
]

app.use("/page", chain) // same as above
app.use("/page", function(req, res){
  if(req.query.setting == "something"){
    return _.simulateRoute(req, res, chain)
  }
  return res.send("no setting")
})
```

Here's my `simulateRoute` function.

```javascript
function simulateRoute(req, res, middlewares){
  function fakeNext(){
    return "next"
  }
  function createNext(index, req, res){
    return Promise.resolve()
      .then(function(){
        return middlewares[index](req, res, fakeNext)
      })
      .then(function(action){
        console.log(action)
        // console.log("/////action/////")
        // console.log(action)
        // console.log("/////index/////")
        // console.log(index)
        if(action == "route") return "route"
        if(action == "next"){
          if(middlewares.length-1 >= index+1){
            return createNext(index+1, req, res)
          }else{
            return "next"
          }
        }
        return "next" // changed from done
      })
  }
}
```

My problems are as follows

* Doesn't this exist somewhere within `express-promise-router` or `express`?
* This only supports promised middlewares (I guess I can pass in next as well and call the original next function)

This ties in with some of the stuff I was talking about here https://github.com/strongloop/express/issues/2709

**Comment by reggi** [comment]
My goal is to have the ability to run a chain of middleware (promised (using [`express-promise-router`](https://github.com/alex-whitney/express-promise-router) or native) without a route, or pass in `req` and `res` from an existing route. This would greatly solve all of my problems.

**Comment by mormahr** [comment]
May i close this or is this still relevant?
