### ISSUE TITLE
Support Promise.resolve(null) to return next

### ISSUE THREAD

**Issue by reggi** [express-promise-router/express-promise-router#16]
I've made a library and I'm trying to support both express' router and this one.

The value from the promise function returns the value of `next`.

The problem is that the when `next()` is passed "next" as in `next("next")` it receives it as an error.

Ideally I can run code like this:

For [`express-promise-router`](https://github.com/alex-whitney/express-promise-router).

```
var promiseRouter = require("express-promise-router")()
promiseRouter.get("/hello-two", function(req, res){
  return somePromise()
})
```

For express' router

```
var expressRouter = require("express").Router()
expressRouter.get("/hello-one", function(req, res, next){
  return somePromise().then(next)
})
```

Ideally `Promise.resolve(null)` was supported to return next as well as next, that way I can pass the value `null` into next and get the next route.

```
Promise.resolve(null).then(next) // no error
Promise.resolve("next").then(next) // error
```

Currently I have to write this & don't worry about errors because they're caught and returned.

```
var expressRouter = require("express").Router()
expressRouter.get("/hello-one", function(req, res, next){
  return somePromise().then(function(val){
    if(val == "next") return next()
    return next(val)
  })
})
```

Thoughts?

**Comment by TheThing** [comment]
I think your solution would be to change:

```javascript
return somePromise().then(next)
```
to
```javascript
return somePromise().then(() => next())
```

That is what I do if I have to call stuff like `next` or [`done`](https://mochajs.org/#asynchronous-code) from promises.

Also, next is primarily being used to be called either empty (no value = everything was success) or with an error (parameter = something went wrong) so passing it directly into then like `.then(next)` would be serious anti pattern as anything that gets resolved, any value or anything will suddenly be interpreted as an error. The more correct pattern would be:

```javascript
return somePromise().then(() => next()).catch(next)
```

Effectively what you're with this code:

```javascript
return somePromise().then(function(val){
    if(val == "next") return next()
    return next(val)
  })
```

Is turning any and all values (excluding the literal value `"next"` that is being resolved (remember, resolved = success) as a failure which is pretty serious antipattern as I mentioned.

**Comment by TheThing** [comment]
Oh wow, I just took a better look at the code and now I realize what your problem is. The problem that I see though with making `Promise.resolve(null)` call next  is routes will probably most likely return null under normal circumstances.

**Comment by mormahr** [comment]
May i close this or is this still relevant?

**Comment by TheThing** [comment]
I'd say so, I don't think this feature should be implemented imo.

**Comment by mormahr** [comment]
Nice. I like cleanup 👍
