### ISSUE TITLE
Some thoughts on returning json / text

### ISSUE THREAD

**Issue by rikkertkoppes** [express-promise-router/express-promise-router#17]
I like this idea a lot, especially when it comes to error handling.

However, by far the most common use case would be to send json or text. What would you think about the following:
- when the promise rejects, call `next(err)`
- when the promise resolves with text, call `res.send(text)`
- when the promise resolves anything else, call `res.json(obj)`
- `next()` and `next('route')` seem like exceptional cases to me, what about just not handling those?

**Comment by heycalmdown** [comment]
+1

**Comment by joepie91** [comment]
This seems like dangerous functionality. *Especially* with implicit returns (ES6 arrow functions, CoffeeScript, ...), it would be very easy to accidentally return (and thus expose) data that the user is never meant to see.

**Comment by bisubus** [comment]
+1. There is no reason to limit the magic to `next`. Similarly, I've worked out some conventions for generator/promise resolutions in [express-ko](https://github.com/ex-machine/express-ko), and after some refactoring they began to work perfectly for us.

@joepie91 I don't think that human errors should be taken into account. Arrow's implicit return is a powerful feature, and using it properly may be a tough lesson but it has to be learned.

**Comment by joepie91** [comment]
@bisubus Anything that doesn't take human error into account, is flawed and dangerous right out of the gate.

Humans make mistakes, regardless of their competence level, and this is in fact precisely what made things such a mess to begin with - and also precisely what Promises try to address by failing loudly when an error is not handled, as opposed to ignoring it silently like happens in error-first callbacks.

Let's not knowingly introduce more pitfalls for developers and end users. There are enough that need to be solved as-is.

**Comment by mormahr** [comment]
As the last comment is over a year old i'd like to close this issue (and #11, #16). But if anyone is interested in pushing these thoughts in a new direction (eg. by wrapping the response or by configuring this functionality "opt-in") we could open a new issue.
