### ISSUE TITLE
List all routes

### ISSUE THREAD

**Issue by subhisamara** [express-promise-router/express-promise-router#309]
Hi, 
is there any way to list all the routes?

**Comment by mormahr** [comment]
Starting with v4.1.1 of `express-promise-router` you should be able to inspect `router.stack` (#306 #307). It's easiest to do it with [`express-list-endpoints`](https://www.npmjs.com/package/express-list-endpoints).

Hope this helps, if you have more questions please [open a discussion in the Q&A category](https://github.com/express-promise-router/express-promise-router/discussions/new?category=q-a)
