### ISSUE TITLE
Please release new version to NPM

### ISSUE THREAD

**Issue by dolbyzerr** [express-promise-router/express-promise-router#40]
The last version in npm is `1.1.1`.

I am interested in native Promises in particular.

**Comment by mormahr** [comment]
No it's not. (Just kidding, i published it two seconds ago)

Sorry i have been using 2.0.0-alpha.1 (which was / is available thru npm) for the past month(s) and just haven't found the time to finish the documentation. So thanks for the reminder :)

**Comment by dolbyzerr** [comment]
@mormahr Thanks! :)
