### ISSUE TITLE
Remove/Reduce lodash usage

### ISSUE THREAD

**Issue by SimonSchick** [express-promise-router/express-promise-router#41]
You are only using 2 of lodash's function, one can be replaced with a `for in` loop, the other can be replaced with https://www.npmjs.com/package/lodash.flattendeep.

**Comment by SimonSchick** [comment]
Furthermore, since you are already dropped support for old node versions, you can also get rid of `methods`.

**Comment by mormahr** [comment]
I know, unfortunately haven't had the time. I wanted to completely get rid of flattenDeep but then got distracted by other work. Maybe i'll do this as a intermediate solution. 🤔

**Comment by SimonSchick** [comment]
I think dropping 2 deps for 1 micro would be enough for now.

**Comment by SimonSchick** [comment]
Also if you wanna be a total bro adding TypeScript typings would be awesome!

**Comment by mormahr** [comment]
Hah! As i‘m heavily relying on Flow for my own projects (i took over maintenance for this project, so it‘s not my „own“ codebase) i tried to add flowtypes to this aswell, but this code is mutating existing prototypes/classes that aren’t really typed to be modified. It should be possible to create a library definition, though.

As i’m not familiar with TypeScript i won’t create one for TypeScript but others are free to contribute one, but i’m not entirely sure what the TypeScript way to do is (include in npm module or contribute to DefinitelyTyped).

**Comment by mormahr** [comment]
I just rechecked and `methods` is a dependency of `express`, so there is no benefit in removing it, as it will be installed anyway. It even has a drawback: [Express uses `methods` to determine available methods](https://github.com/expressjs/express/blob/351396f971280ab79faddcf9782ea50f4e88358d/lib/router/route.js#L192), so if we use `http.METHODS` instead, they might mismatch.

**Comment by mormahr** [comment]
See v3.0.0-rc.1

**Comment by mormahr** [comment]
This is now released and TypeScript definitions have been added as well (#47)
