### ISSUE TITLE
Changing license / attribution information

### ISSUE THREAD

**Issue by mormahr** [express-promise-router/express-promise-router#52]
As project maintenance has changed since this project was started in 2014 i'd like to change the "license" section of the readme.

I propose going with something like this:

```markdown
## Attribution
Licensed under the [MIT license](LICENSE).

Initial implementation by [Alex Whitney](https://github.com/alex-whitney) \
Maintained by [Moritz Mahringer](https://github.com/mormahr) \
Contributed to by [awesome people](https://github.com/express-promise-router/express-promise-router/graphs/contributors)
```

It would be awesome to have everybody that contributed listed individually, but i think the link will do in the meantime.

As this mostly your code @alex-whitney, i'd like to hear what you think about it.
For the same reason i'd like to update `package.json` to have new contact information.

**Comment by alex-whitney** [comment]
Sorry - I totally missed this notification. I'm more than OK with this :+1:

**Comment by mormahr** [comment]
This is covered by #62.
