### ISSUE TITLE
Regex route broken

### ISSUE THREAD

**Issue by zachauten** [express-promise-router/express-promise-router#58]
I have a route `/threads/:threadId(\d+)` that i'm calling like `/threads/1`

It gives a 404 when I include the regular expression but when I use the route `/threads/:threadId` and call `/threads/1` it returns a 200 along with the data i'm expecting. 

The documentation doesn't mention anything about regular expressions working differently that plain express router, so I'm assuming this behavior is unexpected.

**Comment by douggr** [comment]
As stated in [express docs](http://expressjs.com/en/guide/routing.html), you need to escape slashs `\` in RegEx routes:

```
Because the regular expression is usually part of a literal string, be sure to escape 
any \ characters with an additional backslash, for example \\d+.
```
