### ISSUE TITLE
[Question] Proper route structure for post routes

### ISSUE THREAD

**Issue by Pk13055** [express-promise-router/express-promise-router#60]
What is the correct way to structure post routes?
My code:
```javascript
const Router = require('express-promise-router');
const router = new Router();
router.post('/contact', async (req, res, next) => {
	console.log(req.fields);
	return Promise.resolve("back");
});
```
The problem: This route neither returns back after execution nor does it actually log out the request fields.

**Comment by mormahr** [comment]
Do you mean "return" in the sense of "return to the user via HTTP"? We intentionally don't support sending the result of the promise chain to avoid mistakes, that accidentally send internal application state. 

```js
const Router = require('express-promise-router');
const router = new Router();
router.post('/contact', async (req, res, next) => {
	const greeting = await database.getGreeting()
        res.send(greeting)
});
``` 

If `getGreeting()` throws an error the express error handling will kick in and show your error route. Otherwise for the "normal" data flow you use `res.send` as you would with plain express.

Did this answer your question?

**Comment by Pk13055** [comment]
So let's say I have a simple form at `/login/`:
```html
<form method="POST" action>
   <input type="text" name="name">
   <button type="submit">
```
This is served by:
```js
router.get('/login', async (req, res, next) => {
	res.render('user/login', { title: 'Signout' });
});
```

Now I want to `POST` this to a route:
```js
router.post('/login', async (req, res, next) => {
        // some async/await route functionality
        let postData = json.load(req.body);
        // I want to return back to the get method after processing ->
        return Promise.resolve('back'); // as mentioned in the documentation
});
```
What would be the "correct" way to go about doing this?

**Comment by mormahr** [comment]
I'm not sure what is not working for you and what your expectation is.

1. POST data should be parsed by a middleware ([like so](http://expressjs.com/de/api.html#req.body))
`let postData = json.load(req.body);`
Not sure what `json.load` is supposed to represent.

2. `return Promise.resolve('back'); // as mentioned in the documentation` which documentation? We mention `next` and `route`.

> Calling next() and next('route') is supported by resolving a promise with either 'next' or 'route'. **No action is taken if the promise is resolved with any other value**. [Emphasis mine]

---

If you want to parse the body, do something and then redirect back i recommend this:

```js
var multer = require('multer')
router.use(bodyParser.json())

router.post('/login', async (req, res, next) => {
        // some async/await route functionality
        
       console.log(req.body) // should now contain the values

        // redirect back to login route
        res.redirect("/login")
})
```
