### ISSUE TITLE
Thrown errors get passed to client but no stack trace output on server.

### ISSUE THREAD

**Issue by fadedbee** [express-promise-router/express-promise-router#61]
Thanks for writing express-promise-router, even with this problem it's better than the two other express/async approaches I have tried.

My problem is with:
```

const express = require('express');
const Router = require('express-promise-router');
const router = new Router();

router.get('/some_path', async function(req, res, next) {
  throw new Error('error');
  res.json({foo: 'bar'});
});

module.exports = router;
```

When this is run, an error page is sent to the client (as expected) but the only thing output on the server is:

`GET /some_path 500 1.406 ms - 1045`

With the non-async router, I get a full stack trace in the server's output.

Is there a way of making the express-promise-router produce a full stack trace on the server?

**Comment by mormahr** [comment]
Hi there,

using this

```js
const express = require('express');
const app = express();
const Router = require('express-promise-router');
const router = new Router();

router.get('/async_error', async function(req, res, next) {
    throw new Error('error');
    res.json({foo: 'bar'});
});

router.get('/async_delay_error', async function(req, res, next) {
    return new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error('delayed')), 1000);
    });
});

router.get('/sync_error', function(req, res, next) {
    throw new Error('error');
    res.json({foo: 'bar'});
});

app.use(router);
app.listen(3001);
```

i get stack traces for all routes, on the console as well as the http client. Could you provide an example that reproduces the behavior you describe?

**Comment by mormahr** [comment]
I'm closing this, as this issue has been inactive for 5 months. If you still have questions, please comment and i'll reopen.
