### ISSUE TITLE
Error when used in overnightjs project

### ISSUE THREAD

**Issue by andrewmackrodt** [express-promise-router/express-promise-router#64]
Caused by incorrect placing of parentheses during the `isArray` check.

**Existing**
https://github.com/express-promise-router/express-promise-router/blob/6bf785ae1f04e12cb209745642d377cb99a80020/lib/express-promise-router.js#L80

**Modified**
```js
(Array.isArray(args[0]) && ('string' === typeof args[0][0] || args[0][0] instanceof RegExp))
```

Possibly relates to https://github.com/express-promise-router/express-promise-router/issues/46

**Comment by soulstar205** [comment]
I removed the parenthesis, but the error paersists

**Comment by andrewmackrodt** [comment]
Have a look at the **modifed** snippet above, I've been using this for about 6 months.

**Comment by soulstar205** [comment]
thank you for your prompt response, but I did make the same modification as
the snippet below it.
The same error persisted
Here;

C:\Users\Acer\Documents\React\chatW\server\ApiAuthentication\node_modules\express-promise-router\lib\express-promise-router.js:80
                (Array.isArray(args[0]) && 'string' === typeof args[0][0]
|| args[0][0] instanceof RegExp)

        ^

TypeError: Cannot read property '0' of undefined
    at Route.instanceToWrap.(anonymous function) [as get]
(C:\Users\Acer\Documents\React\chatW\server\ApiAuthentication\node_modules\express-promise-router\lib\express-promise-router.js:80:85)
    at Object.<anonymous>
(C:\Users\Acer\Documents\React\chatW\server\ApiAuthentication\routes\users.js:14:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

**Comment by andrewmackrodt** [comment]
Your error trace shows you haven't made the modification:

Yours:
`(Array.isArray(args[0]) && 'string' === typeof args[0][0]
|| args[0][0] instanceof RegExp)`

Expected:
`(Array.isArray(args[0]) && ('string' === typeof args[0][0] || args[0][0] instanceof RegExp))`

**Comment by soulstar205** [comment]
I see it now, thanks, I'll apply the change and hopefully everything works
out

**Comment by soulstar205** [comment]
That appeared to solve that problem, however a new one developed, please
take a look at the error message

    throw new Error(msg);
        ^

Error: Expected a callback function but got a [object Undefined]
    at wrapHandler
(C:\Users\Acer\Documents\React\chatW\server\ApiAuthentication\node_modules\express-promise-router\lib\express-promise-router.js:10:15)
    at
C:\Users\Acer\Documents\React\chatW\server\ApiAuthentication\node_modules\express-promise-router\lib\express-promise-router.js:87:24
    at Array.map (<anonymous>)
    at Route.instanceToWrap.(anonymous function) [as get]
(C:\Users\Acer\Documents\React\chatW\server\ApiAuthentication\node_modules\express-promise-router\lib\express-promise-router.js:86:38)
    at Object.<anonymous>
(C:\Users\Acer\Documents\React\chatW\server\ApiAuthentication\routes\users.js:14:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apiauthentication@1.0.0 server: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apiauthentication@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2020-03-19T14_52_26_076Z-debug.log

**Comment by andrewmackrodt** [comment]
That is a different issue, if you believe you're using the library correctly I'd recommend creating a new issue.

**Comment by mormahr** [comment]
I want to merge a fix for this, but i'd like to have a failing test case.
Can someone tell me in which cases this fails / provide an example?

The parameter would have to be neither string, regex nor array, if i skimmed over this correctly.

**Comment by andrewmackrodt** [comment]
In my instance this was caused by incorrect usage of overnightjs (potentially a bug in overnightjs itself) and possibly covered in the [FAQ](https://github.com/express-promise-router/express-promise-router#cannot-read-property-0-of-undefined). I still believe this issue to be valid but cannot think of a failing test case when the library is used correctly.

```ts
import {Controller, Delete, Get, Options, Patch, Post, Put} from '@overnightjs/core'
import {Request, Response} from 'express'
import {constants as status} from 'http2'

@Controller('*')
export class NotFoundController {
    // these routes are ok
    @Options('') public optionsNotFound(req: Request, res: Response) { this.notFound(req, res) }
    @Get('') public getNotFound(req: Request, res: Response) { this.notFound(req, res) }
    @Patch('') public patchNotFound(req: Request, res: Response) { this.notFound(req, res) }
    @Put('') public putNotFound(req: Request, res: Response) { this.notFound(req, res) }
    @Post('') public postNotFound(req: Request, res: Response) { this.notFound(req, res) }

    // this one will cause the error
    @Delete() public deleteNotFound(req: Request, res: Response) { this.notFound(req, res) }

    private notFound(req: Request, res: Response) {
        res.status(status.HTTP_STATUS_NOT_FOUND).json({error: 'Not Found'})
    }
}
```
When a "correct" route is defined, `args[0]` is a callback so the check for `args[0][0]` does not fail. In the "incorrect" route example, `args` is empty so `args[undefined][0]` throws the error.
